### ISSUE TITLE
libretube.net is not an official site

### ISSUE THREAD

**Issue by aeongdesu** [libredirect/libredirect.github.io#2]
> currently, codeberg has blocked create new account, so I leave it here.

https://github.com/libredirect/libredirect.github.io/blob/b14d35342df5a8ecb9a2e020fa788133c8fb8240/mobile.html#L40

**libretube.net is not an official site!**
the real site is libretube.dev. (https://github.com/libre-tube/LibreTube/issues/4409#issuecomment-1725840341)

**Comment by ManeraKai** [comment]
Alright, can you create a pull request?

**Comment by Darin755** [comment]
I'm not sure if anyone has filed a complaint yet but I noticed that this domain is registered under namecheap. You should report the abuse here

https://www.namecheap.com/support/knowledgebase/article.aspx/9196/5/how-and-where-can-i-file-abuse-complaints/

Keep in mind only the owner of this project can complain. If you wait too long you will be unlikely to be able to take down other fake sites in the future as it sets precedent every time you ignore fake sites. (Not a lawyer)
