### ISSUE TITLE
Remove references to Twitter as LibRedirect no longer supports Nitter

### ISSUE THREAD

**Issue by antermin** [libredirect/libredirect.github.io#8]
Following https://github.com/libredirect/browser_extension/commit/b6c98028b991c66d3f417023eb391683c09a8728, we should no longer claim that this extension redirects Twitter requests.

Examples:
* https://github.com/libredirect/libredirect.github.io/blob/c4204623c525a98e201eb352318e7ac2f148430a/index.html#L15
* https://addons.mozilla.org/en-US/firefox/addon/libredirect/ (Add-on description on AMO)

**Comment by IkelAtomig** [comment]
Since Nitter is reinstated (Added back in code), Closing this. It will be released sooner.
